//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpuRaspParser.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int id { get; set; }
        public string School { get; set; }
        public string Course { get; set; }
        public string Groupname { get; set; }
        public string Link { get; set; }
    }
}
